### ISSUE TITLE
Keine Fehlermeldung, falls der Parameter kein gültiges Verzeichnis darstellt

### ISSUE THREAD

**Issue by niklaspolke** [mkymikky/DupFinder#11]
Übergibt man dem Programm einen Parameter, der kein gültiges Verzeichnis darstellt (so wie ich gerade z.B. "C;\test" (Semikolon statt Doppelpunkt), dann gibt es eine leere Ergebnismenge ohne Hinweis auf die Falscheingabe.

**Comment by mkymikky** [comment]
Wenn das Programm ohne Pfadangabe startet, würde ich direkt zu Maske mit der Pfadeingabe wechseln.
Mit Pfadangabe sollte der Suchvorgang direkt starten, hierbei muss er spätestens vom DuplicateLengthFinder sauber validiert werden.
Ich schaue mir das mal an.

**Comment by mkymikky** [comment]
Die Fehlermeldungen aus dem DuplicateLengthFinder sollten jetzt helfen, das Programm korrekt zu benutzen. @niklaspolke bitte reviewen, ob der Punkt schon gelöst ist.

**Comment by FunThomas424242** [comment]
Aus meiner Sicht ausreichend gelöst.

**Comment by niklaspolke** [comment]
Ich finde einen Stacktrace zwar nicht schön als Fehlermeldung für den Anwender, aber das genaue Problem ist ja enthalten:

> Exception in thread "main" java.lang.IllegalArgumentException: Not existing path: asdf

Aus meiner Sicht ausreichend gelöst.

**Comment by FunThomas424242** [comment]
Beim mir erscheint es vernünftig ohne Stacktrace
```
huluvu424242@stachel:~/git/DupFinder$ java -jar target/DupFinder-0.0.1-SNAPSHOT.jar 
FEHLER: Parameter <Verzeichnis> fehlt
 usage: DupFinder <Verzeichnis>
<Verzeichnis> = Verzeichnis in dem rekursiv nach Duplikaten gesucht wird
huluvu424242@stachel:~/git/DupFinder$ 
```

@niklaspolke  Wie rufst Du das Programm auf? Hast die aktuellste Version?

**Comment by FunThomas424242** [comment]
Ah ok, als Parameter einen Folder genutzt den es nicht gibt. Ja das könnte schöner sein ;)
```
huluvu424242@stachel:~/git/DupFinder$ java -jar target/DupFinder-0.0.1-SNAPSHOT.jar 
FEHLER: Parameter <Verzeichnis> fehlt
 usage: DupFinder <Verzeichnis>
<Verzeichnis> = Verzeichnis in dem rekursiv nach Duplikaten gesucht wird
huluvu424242@stachel:~/git/DupFinder$ java -jar target/DupFinder-0.0.1-SNAPSHOT.jar asdd
Exception in thread "main" java.lang.IllegalArgumentException: Not existing path: /home/huluvu424242/git/DupFinder/asdd
	at de.b0n.dir.processor.DuplicateLengthFinder.<init>(DuplicateLengthFinder.java:33)
	at de.b0n.dir.processor.DuplicateLengthFinder.getResult(DuplicateLengthFinder.java:169)
	at de.b0n.dir.processor.DuplicateLengthFinder.getResult(DuplicateLengthFinder.java:148)
	at de.b0n.dir.DupFinder.main(DupFinder.java:41)
huluvu424242@stachel:~/git/DupFinder$ 
```

**Comment by niklaspolke** [comment]
@FunThomas424242 Meine Fehlermeldung kommt nur, wenn Du ein Verzeichnis eingibst, welches aber nicht existiert (wie in meinem Beispiel der String asdf)

**Comment by mkymikky** [comment]
Aus meiner Sicht kann mit den bisherigen Korrekturen die Main-Klasse implementiert werden, um sinnvoll auf die Parameter zu reagieren.
Ich überlege mir dazu etwas.

**Comment by FunThomas424242** [comment]
Hab da mal einen Vorschlag erarbeitet. Recht einfach aber evtl. ausreichend.

**Comment by FunThomas424242** [comment]
Ach herje ich hab das @Ignore noch im DupFinderTest vergessen.
@mkymikky Bitte mal rausnehmen, dann sollte die Coverage steigen.

**Comment by FunThomas424242** [comment]
So fertig - jetzt kann gemergelt werden ;)

**Comment by FunThomas424242** [comment]
Jippi kann geschlossen werden.
