### ISSUE TITLE
Anzeige und Interaktion

### ISSUE THREAD

**Issue by FunThomas424242** [mkymikky/DupFinder#12]
Für meine Verwendung (Datenbestand sichten und Dubletten an eine Ort zusammen ablegen) würde ich folgende GUI bevorzugen:

### Darstellung 
-- Filename1  (Filesize1)
---- Ort 1
---- Ort 2
---- Ort 3
-- Filename1 (Filesize2)
---- Ort A
---- Ort B
-- Filename2 (Filesize1)

### Sortierung
Idealerweise sortiert nach 1. Filename alphabetisch und 2. Filesize.

### Aktionen
Als Aktionen bräuchte ich:

* Kontextmenü auf Ort "Hierher verschieben"
(Dabei werden die Duplikate aus den anderen Orten an den selektierten Ort verschoben. Damit es nicht zu Namenskonflikten kommt sollte eine Umbenennung durchgeführt werden z.B. anhängen bak1, bak2, ... oder so. Vor Ausführung der Aktion muss geprüft werden ob dort bereits Dateien mit den Zielnamen abliegen - dann halt Hinweis und nicht ausführen)
* Für Konflikte beim Zusammenziehen sollte man per Kontextmenü an jedem Ort hinterlegen können wie die Datei umbenannt wird also bak1 oder dup1 oder ... )

### Development

Zur Realisierung würde ich GUI und SuchLib auf separate Projekte auteilen z.B. AggregatorBuild in maven.

**Comment by mkymikky** [comment]
Eine vielseitige Oberfläche finde ich prima.
Ich würde aber auch dazu tendieren, die Oberfläche von der Logik zu trennen.

In meiner Vorstellung kann der DupFinder genau das: Dubletten anhand von Aufrufparametern zu finden, und das mit Textausgaben zu Fehlern und Ergebnissen zurück zu liefern.
Gleichzeitig bietet er eine Programmierschnittstelle, um eine grafische Oberfläche oder den Einbau in ein größeres Programm zu unterstützen.

Daher würde ich mich freuen, wenn ein (neues?) Projekt den DupFinder verwendet und gleichzeitig DupFinder sich auf die Suche konzentriert.

**Comment by FunThomas424242** [comment]
Ich hab da mal kurz einen Rahmen erstellt. Werde die nächste Zeit aber nicht gleich dazu kommen. In der Zeit könnt Ihr ja auf waffle.io dazu ein paar Task einstellen. 
* [Github Home](https://github.com/FunThomas424242/DupFinder-GUI)
* [Waffle Home](https://waffle.io/FunThomas424242/DupFinder-GUI)
