### ISSUE TITLE
Artefakt von DupFinder steht nicht zur Verfügung

### ISSUE THREAD

**Issue by mkymikky** [mkymikky/DupFinder#16]
Um andere Projekte mit den Fähigkeiten von DupFinder auszustatten, muss das Artefakt als Dependency auflösbar sein.

**Comment by FunThomas424242** [comment]
Ich hab mir mal einen Branch gezogen vom aktuellen mkymikky/master mit commit 028c8b9679c373c4d19385a274fda3c19c6b3e86. Er läuft bei mir unter [#16_to_mkymikky](https://github.com/FunThomas424242/DupFinder/tree/%2316_to_mkymikky) und sollte sich später als PullRequest mergen lassen. 

Was genau ist zu tun? 
pom.xml soweit ergänzen, dass Du bis maven central deployen kannst? Weiß ich aktuell was alles zu tun wäre. Soll ich loslegen oder schwebt Dir was anderes vor?
(Vorraussetzung damit das später funktioniert sind Accounts auf bintray und bei sonatype aber das kann man zum Schluss angehen).
