### ISSUE TITLE
Verwendung als Library

### ISSUE THREAD

**Issue by FunThomas424242** [mkymikky/DupFinder#17]
Bitte mal ein Beispiel geben wie das Programm aktuell als Library z.B. von einer GUI aufzurufen ist. 
Ich hätte folgende Dinge erwartet:
* Einen Konstruktor um selbst eine Instanz erzeugen zu können - zur Not geht auch ein statischer Aufruf über die main(String[]) Methode - find ich aber nicht so schön. 
* Methode zur Registrierung eines Callbacks welches immer bei einem neuen Suchergebnis/Arbeitsschritt oder ähnlichem eine Methode aufruft welches z.B. die GUI über diese Neuigkeit informiert. 
* eine Methode um das Gesamtergebnis abzugreifen. Idealerweise nix generisches wie Queue sondern irgendwas fachliches wie Suchergebnis oder so.

**Comment by mkymikky** [comment]
Die Algorithmen im inneren sind einzeln aufrufbar und auch einzeln sinnvoll. Daher haben diese bereits eine statische Methode, um sie aufzurufen.
Die Konsolenanwendung dient als Verwendungsbeispiel.
Die fachliche Kapselung und der Callback werden für die Prozessoren in den Requests #18 und #19 weiterbehandelt.
