### ISSUE TITLE
Vermuteter Deadlock im Programm

### ISSUE THREAD

**Issue by niklaspolke** [mkymikky/DupFinder#2]
Wenn die Suche beendet ist, gibt es keinen Hinweis. Gerade bei längeren Suchen auf Nicht-SSD Festplatten muss man die CPU-Last oder Laufwerksaktivität checken um zu wissen, ob er noch sucht oder bereits fertig ist.

**Comment by niklaspolke** [comment]
Vermutlich ist es eher ein Bug, dass es zu einem Abbruch oder Dead-Lock des Programms kommt. Bei simplen Verzeichnissen läuft das Programm durch und gibt als Ergebnis die benötigte Zeit in Sekunden an.
Wenn ich aber z.B. C:\ als Verzeichnis wähle, hört er irgendwann auf mit Ausgaben, CPU- und Festplattenlast sind nicht gegeben und das Programm hat keine Meldung bzgl. benötigter Zeit ausgegeben.

**Comment by mkymikky** [comment]
Dieser Fall steht vermutlich in Zusammenhang mit meiner Beobachtung:
Bei der Ausgabe der Statusmeldungen kann es zu dem Fall kommen, dass nach der Schlussmeldung noch eine Bearbeitungsmeldung nachkommt, welche dann nicht mehr überschrieben wird.
Dieser Fehler sollte sporadisch auftreten.
Hier hilft nur ein sauberes Threading-Design auch bezüglich der Statusmeldungen.

Daher: Ist der in diesem Issue beobachtete Fehler sporadisch?

**Comment by niklaspolke** [comment]
Aktuell läuft die Suche innerhalb eines sehr kleinen Verzeichnisses (Git-Repository) nur bei einem von 8 mal erfolgreich durch.

**Comment by mkymikky** [comment]
Würdest du bitte einen Stacktrace von so einem Deadlock bereitstellen?

**Comment by mkymikky** [comment]
Das Problem konnte ich reproduzieren, nachdem ich einige Stacktraces eliminiert habe.
Die genaue Ursache suche ich gerade.

**Comment by mkymikky** [comment]
Es sieht so aus, dass der Fehler durch ungleich große Dateien ausgelöst wird.
Bei der Fehlerbehandlung werden die unlesbaren Dateien nicht entfernt und lösen dadurch eine Endlosschleife aus.

**Comment by mkymikky** [comment]
@niklaspolke : Bitte bei weiteren bestehenden Deadlocks erneut benachrichtigen.
