### ISSUE TITLE
NullPointerException bei Zugriff auf eingeschränkte Verzeichnisse

### ISSUE THREAD

**Issue by mkymikky** [mkymikky/DupFinder#20]
Beim lese-Versuch tritt bei geschützten Verzeichnissen unter Windows ("System Volume Information" und andere) eine NPE im DuplicateLengthFinder.DuplicateLengthRunner in Zeile 85 auf.

Hotfix in Vorbereitung

**Comment by mkymikky** [comment]
Als nächstes integriere ich diese Info in den Callback, damit ist der Bug dann gefixt.

**Comment by mkymikky** [comment]
Mit commit 9668b2e148c73be89d23932a693b327cf3f4a995 gefixt.

**Comment by mkymikky** [comment]
Bug noch reproduzierbar: Zugriff auf Unterverzeichnis des Windows Papierkorbs.

**Comment by FunThomas424242** [comment]
Ich würde als erstes die checkFolder Methode optimieren. Aus meiner Sicht könnten mehrere Bedingungen für einen Folder vorliegen. Zum Beispiel könnte ein leerer nicht lesbarer Folder vorliegen. Dann würde ich beim Ermitteln der Liste schon eine PermissionException erwarten, noch bevor canRead ermittelt werden kann. Bei der ersten Fehlerbedingung würde ich mit Exception aussteigen - wozu eine Message als Rückgabewert? Für den Nutzer? Genügt da nicht ein logging vor dem Werfen einer Exception?
Ein Stacktrave wäre gut gewesen, aktuell ist die Zeile 85 ein Kommentar.

**Comment by mkymikky** [comment]
Dies ist einer der wahrscheinlichen Root-Causes für Fehler #2, den ich aktuell bearbeite. Dabei hat sich die Struktur verändert, weswegen dieses Issue nicht mehr auftritt.
Review in #2 willkommen.
