### ISSUE TITLE
Fehlende Sortiermöglichkeit

### ISSUE THREAD

**Issue by niklaspolke** [mkymikky/DupFinder#3]
Es wäre hilfreich, wenn man die gefundenen Dateiduplikate sortieren kann, z.B. nach

- Dateiendung
- Größe
- Ort/Name der Datei

**Comment by mkymikky** [comment]
Ich kann den Wunsch nach Sortierung gut nachvollziehen.
Ich kann mir zwei Umsetzungspfade dafür vorstellen:
- Umbau der Anzeige auf eine Tabelle -> hier würde die native Sortierung zusammengehörige Dubletten wohl auseinanderreißen
- Implementierung der Sortierung mittels Filtern -> Hier müssten Comparatoren für die DuplicateTreeNodes pro Sortierung bereitgestellt werden.
Ich würde den zweiten Ansatz bevorzugen. Was meinst du @niklaspolke ?

**Comment by niklaspolke** [comment]
Zweiter Ansatz klingt gut. Ich würde ihn wie folgt präzisieren:

- Zuerst Sortierung innerhalb einer DuplicateGruppe (so dass das Element das Parent-Element ist, was laut Sortierung am weitesten oben steht).
- Danach Sortierung der Parent-Elemente der Gruppen.

(trifft nur auf Ort-Sortierung zu, bei den anderen Attributen sind ja alle Duplikate gleich)

**Comment by mkymikky** [comment]
Wird in @FunThomas424242 weiterverfolgt

**Comment by FunThomas424242** [comment]
Bitte einen Task  unter https://waffle.io/FunThomas424242/DupFinder-GUI anlegen.
