### ISSUE TITLE
Encoding falsch

### ISSUE THREAD

**Issue by niklaspolke** [mkymikky/DupFinder#4]
Die Dateien scheinen UTF-8 zu sein, doch die Ausgabetexte sowie der Quellcode werden mit falschen Umlauten angezeigt.

**Comment by FunThomas424242** [comment]
Scheint nur den DuplicateLengthFinder zu betreffen. Ich versuch mich da mal dran :)

**Comment by FunThomas424242** [comment]
Bitte schließen - ist aus meiner Sicht erledigt.
