### ISSUE TITLE
Code Review FileStream

### ISSUE THREAD

**Issue by FunThomas424242** [mkymikky/DupFinder#6]
Irgendwas passt hier nicht.
[FileStream](https://github.com/mkymikky/DupFinder/blob/master/src/main/java/de/b0n/dir/processor/FileStream.java#L34-L44)

Entweder wir lassen die close Methode weg oder wir geben den Stream nicht raus - beides zusammen ist ungut. Der Stream wird gewöhnlich von dem geschlossen der ihn benutzt. Der kann den Stream auch in den nächsten Stream reinstecken, dann wird er beim Aufruf der close Methode des äußeren Stream's geschlossen. <del>Ein zusätzlicher Versuch dann nochmal ein close durchzuführen wird garantiert bestraft. </del>

Also wenn die Klasse schon Stream heißt wäre das Weglassen von getStream wohl richtig. Mein Gefühl sagt mir aber es ist besser ohne close und dann lieber die Klasse sinnvoll benennen. Irgendwie ist sie ja nur ein Wrapper um damit leichter arbeiten zu können oder?

Ach und wenn die getStream() immer einen neuen Stream erzeugt falls keiner vorhanden ist dann evtl. newStream(). Aber sie macht es ja nicht immer :( dann vielleicht zwei Methoden:
* newStream() als Factory Methode gibt immer einen neuen Stream zurück
* getStream() als Getter gibt immer den wirklich gehaltenen Stream zurück

Oder soll wirklich nur immer eine funktionierende Streaminstanz existieren? Schreib mal was die Klasse machen soll bzw. warum sie gebraucht wird.

**Comment by mkymikky** [comment]
Der veröffentlichte Stream sollte mit Commit 620a5f3 sinnvoll gekapselt sein.
Bitte prüfen.

**Comment by FunThomas424242** [comment]
Jupp.
